### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by masa-1016** [masa-1016/protospace-33390#1]
# URL
https://protospace-33390.herokuapp.com/

**Comment by kouhei-masuda** [comment]
@masa-1016 さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。

**Comment by masa-1016** [comment]
有難う御座いました。
